@startuml
ConcreteObserver -> ConcreteSubject : 主题
Subject -> Observer : 许多观察者
ConcreteObserver ..|> Observer
ConcreteSubject ..|> Subject


interface Subject {
    registerObserver()
    removeObserver()
    notifyObservers()
}
interface Observer {
    update()
}
class ConcreteSubject {
    registerObserver()
    removeObserver()
    notifyObservers()

    getState()
    setState()
}
class ConcreteObserver {
    update()
}
@enduml