@startuml
Subject --|> Observer : 观察者
CurrentCondtionsDisplay --|> Subject : 主题
WeatherData ..|> Subject
CurrentCondtionsDisplay ..|> Observer
CurrentCondtionsDisplay ..|> DisplayElement
StatisticsDisplay ..|> Observer
StatisticsDisplay ..|> DisplayElement
ThirdPartyDisplay ..|> Observer
ThirdPartyDisplay ..|> DisplayElement
ForecastDisplay ..|> Observer
ForecastDisplay ..|> DisplayElement

interface Subject {
    registerObserver()
    removeObserver()
    notifyObserver()
}

interface Observer {
    update()
}

interface DisplayElement {
    update()
}

class WeatherData {
    registerObserver()
    removeObserver()
    notifyObserver()

    getTemperature()
    getHumidity()
    getPressure()
    measurementsChanged()
}

class CurrentCondtionsDisplay {
    update()
    display()
}

class StatisticsDisplay {
    update()
    display()
}

class ThirdPartyDisplay {
    update()
    display()
}

class ForecastDisplay {
    update()
    display()
}
@enduml