@startuml
Client -> Receiver
Client -> ConcreteCommand
ConcreteCommand -> Receiver
ConcreteCommand ..|> Command
Invoker -> Command

class Invoker {
    setCommand()
}

class Receiver {
    action()
}

interface Command {
    execute()
    undo()
}

class ConcreteCommand{
    execute()
    undo()
}
@enduml